# Generated by Django 6.0.6 on 2026-07-05 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Televisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=50, unique=True, verbose_name='Dirección MAC')),
                ('serial_number', models.CharField(blank=True, default='', max_length=50, verbose_name='Número de serie')),
                ('numero_credito', models.CharField(blank=True, default='', max_length=60, validators=[django.core.validators.RegexValidator('^\\d{0,60}$', 'El número de crédito debe contener solo dígitos (máximo 60).')], verbose_name='Número de crédito')),
                ('inhabilitado', models.BooleanField(default=False, verbose_name='Inhabilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'televisor',
                'verbose_name_plural': 'televisores',
                'ordering': ['-created_at'],
            },
        ),
    ]
