# Generated by Django 6.0.6 on 2026-07-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('televisores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='televisor',
            name='eui64',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='EUI-64'),
        ),
    ]
