# Generated by Django 6.0.6 on 2026-07-05 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('televisores', '0002_televisor_eui64'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inhabilitar', models.BooleanField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('corriendo', 'Corriendo'), ('terminado', 'Terminado'), ('error', 'Error')], default='pendiente', max_length=12)),
                ('porcentaje', models.PositiveSmallIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('terminado_en', models.DateTimeField(blank=True, null=True)),
                ('televisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='televisores.televisor')),
            ],
            options={
                'verbose_name': 'sincronización',
                'verbose_name_plural': 'sincronizaciones',
                'ordering': ['-creado'],
            },
        ),
    ]
