# Generated by Django 6.0.6 on 2026-07-06 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('televisores', '0003_syncjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('corriendo', 'Corriendo'), ('terminado', 'Terminado'), ('error', 'Error')], default='pendiente', max_length=12)),
                ('total', models.PositiveIntegerField(default=0)),
                ('procesados', models.PositiveIntegerField(default=0)),
                ('ok_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('creados', models.PositiveIntegerField(default=0)),
                ('actualizados', models.PositiveIntegerField(default=0)),
                ('errores_import', models.JSONField(blank=True, default=list)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('terminado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'sincronización masiva',
                'verbose_name_plural': 'sincronizaciones masivas',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='BulkSyncItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=50)),
                ('inhabilitar', models.BooleanField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('ok', 'OK'), ('error', 'Error')], default='pendiente', max_length=10)),
                ('mensaje', models.TextField(blank=True, default='')),
                ('televisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='televisores.televisor')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='televisores.bulksyncjob')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
