# Generated by Django 6.0.6 on 2026-07-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('televisores', '0004_bulksyncjob_bulksyncitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulksyncitem',
            name='coincide',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulksyncitem',
            name='local_inhabilitado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulksyncitem',
            name='remoto_inhabilitado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulksyncjob',
            name='modo',
            field=models.CharField(choices=[('sync', 'Sincronización'), ('validacion', 'Validación')], default='sync', max_length=12),
        ),
    ]
