# Generated by Django 6.0.6 on 2026-07-06 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('televisores', '0005_bulksyncitem_coincide_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinCodeUsado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=50, verbose_name='Mac Address')),
                ('passcode', models.CharField(max_length=50, verbose_name='Código de Acceso')),
                ('pin_code', models.CharField(max_length=50, verbose_name='Código Pin')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('televisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pincodes_usados', to='televisores.televisor')),
            ],
            options={
                'verbose_name': 'pin code usado',
                'verbose_name_plural': 'pin codes usados',
                'ordering': ['-creado'],
            },
        ),
    ]
