# Generated by Django 6.0.6 on 2026-07-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('televisores', '0007_bulksyncjob_ip_bulksyncjob_usuario_pincodeusado_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulksyncjob',
            name='cancelar_solicitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bulksyncjob',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('corriendo', 'Corriendo'), ('terminado', 'Terminado'), ('error', 'Error'), ('cancelado', 'Cancelado')], default='pendiente', max_length=12),
        ),
    ]
