# Generated by Django 6.0.6 on 2026-07-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('televisores', '0008_bulksyncjob_cancelar_solicitado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulksyncjob',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='pincodeusado',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='syncjob',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='televisor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de registro'),
        ),
    ]
