# Generated by Django 6.0.6 on 2026-07-14 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('televisores', '0009_alter_bulksyncjob_creado_alter_pincodeusado_creado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulksyncjob',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_sync_jobs', to='empresas.empresa', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='pincodeusado',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pincodes_usados', to='empresas.empresa', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='syncjob',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='empresas.empresa', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='televisor',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='televisores', to='empresas.empresa', verbose_name='empresa'),
        ),
    ]
