# Generated by Django 6.0.6 on 2026-07-14 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('televisores', '0011_empresa_por_defecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulksyncjob',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_sync_jobs', to='empresas.empresa', verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='pincodeusado',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pincodes_usados', to='empresas.empresa', verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='syncjob',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='empresas.empresa', verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='televisor',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='televisores', to='empresas.empresa', verbose_name='empresa'),
        ),
        migrations.AddConstraint(
            model_name='televisor',
            constraint=models.UniqueConstraint(condition=models.Q(('serial_number', ''), _negated=True), fields=('serial_number',), name='televisor_serial_unico'),
        ),
    ]
