# Generated by Django 6.0.6 on 2026-07-14 21:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='nombre')),
                ('nit', models.CharField(blank=True, default='', max_length=30, verbose_name='NIT')),
                ('activa', models.BooleanField(default=True, help_text='Si se desactiva, sus usuarios no podrán iniciar sesión.', verbose_name='activa')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['nombre'],
            },
        ),
    ]
