# Generated by Django 6.0.6 on 2026-07-14 23:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Para identificar al integrador, p. ej. "ERP de Google".', max_length=100, verbose_name='nombre')),
                ('prefijo', models.CharField(editable=False, max_length=16, unique=True, verbose_name='prefijo')),
                ('hash_clave', models.CharField(editable=False, max_length=64, verbose_name='hash')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('creada', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True, verbose_name='último uso')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='empresas.empresa', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'API key',
                'verbose_name_plural': 'API keys',
                'ordering': ['-creada'],
            },
        ),
    ]
