# Generated by Django 6.0.6 on 2026-07-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='expira',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expira el'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='ips_permitidas',
            field=models.TextField(blank=True, default='', help_text='IPs o rangos CIDR (uno por línea). Vacío = cualquier IP.', verbose_name='IPs permitidas'),
        ),
    ]
