# Generated by Django 6.0.6 on 2026-07-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('operador', 'Operador'), ('consulta', 'Consulta')], default='consulta', help_text='Perfil de acceso: define qué módulos y acciones puede usar.', max_length=20, verbose_name='rol'),
        ),
    ]
