# Generated by Django 6.0.6 on 2026-07-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_token_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accent',
            field=models.CharField(blank=True, default='neutro', help_text='Preferencia de color de acento de la interfaz.', max_length=20, verbose_name='color de acento'),
        ),
    ]
