# Generated by Django 6.0.6 on 2026-07-14 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('users', '0004_user_accent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Vacío = acceso global (solo administradores generales).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='empresas.empresa', verbose_name='empresa'),
        ),
    ]
